---
# tasks file for onlykey

- name: RedHat tasks
  include: redhat.yml
  when: "'redhat_family' in group_names"

- name: Debian tasks
  include: debian.yml
  when: "'debian_family' in group_names"

- name: Ensure OnlyKey firmware support (both flashing and use)
  copy:
    dest: /etc/udev/rules.d
    src: files/49-onlykey.rules
  register: onlykey_udev
  become: yes
  when: onlykey_support == true
  tags: ["onlykey"]

- name: Update UDEV rules
  shell: "udevadm control --reload"
  become: yes
  when: onlykey_support == true and onlykey_udev.changed
  tags: ["onlykey"]

