---
# tasks file for dell

- name: Fedora tasks
  include: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- name: Ubuntu tasks
  include: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Blacklist nouveau
  lineinfile:
    state: present
    line: blacklist nouveau
    path: /etc/modprobe.d/no-nouveau.conf
    create: yes
  become: yes

- name: Create gpuoff service
  copy:
    src: gpuoff.service
    dest: /etc/systemd/system/
  notify:
    - systemd-reload
  become: yes

- name: Start and enable gpuoff.service
  service:
    state: started
    enabled: yes
    name: gpuoff.service
  become: yes

- name: Set Grub kernel params
  lineinfile:
    state: present
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*$'
    backup: yes
  notify:
    - update-grub
  become: yes
