#!/bin/sh
set -e

ubuntu_packages() {
  sudo apt update -y \
  && sudo apt install software-properties-common -y \
  && sudo apt-add-repository --yes --update ppa:ansible/ansible \
  && sudo apt install ansible -y
}

# basic dist logic from https://get.docker.com/
get_distribution() {
	lsb_dist=""
	# Every system that we officially support has /etc/os-release
	if [ -r /etc/os-release ]; then
		lsb_dist="$(. /etc/os-release && echo "$ID")"
	fi
	# Returning an empty string here should be alright since the
	# case statements don't act unless you provide an actual value
	echo "$lsb_dist"
}

lsb_dist=$( get_distribution )

case "$lsb_dist" in
  ubuntu) ubuntu_packages;;
  pop) ubuntu_packages;;
  *) echo "$lsb_dist not yet supported";;
esac
