---
# tasks file for hashicorp

# By default hashicorp_arch is "386"
- name: Ensure system architecture
  set_fact:
    hashicorp_arch: "amd64"
  when: ansible_architecture == "x86_64"

# Packer
- name: Download Packer
  get_url:
    url: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_{{ hashicorp_arch }}.zip
    dest: "{{ ansible_user_dir }}/Downloads"
  register: packer_archive
  tags: packer

- name: Ensure /opt/packer
  file:
    state: directory
    path: /opt/packer
  become: yes
  register: packer
  tags: packer

- name: Unarchive Packer
  unarchive:
    src: "{{ packer_archive.dest }}"
    dest: "{{ packer.path }}"
  become: yes
  tags: packer

# Terraform
- name: Download Terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_{{ hashicorp_arch }}.zip
    dest: "{{ ansible_user_dir }}/Downloads"
  register: terraform_archive
  tags: terraform

- name: Ensure /opt/terraform
  file:
    state: directory
    path: /opt/terraform
  become: yes
  register: terraform
  tags: terraform

- name: Unarchive Terraform
  unarchive:
    src: "{{ terraform_archive.dest }}"
    dest: "{{ terraform.path }}"
  become: yes
  tags: terraform

# Vagrant
- name: Download and install Vagrant (Fedora)
  dnf:
    name: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_{{ ansible_architecture }}.rpm
    state: present
  become: yes
  when: ( ansible_distribution == 'Korora') or ( ansible_distribution == 'Fedora' )
  tags: vagrant

- name: Download and install Vagrant (Ubuntu)
  apt:
    deb: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_{{ ansible_architecture }}.deb
    state: present
  become: yes
  when: ( ansible_distribution == 'Ubuntu') or ( ansible_distribution == 'Debian' )
  tags: vagrant
