---

- name: Download SpiderOak package
  get_url:
    url: https://spideroak.com/getbuild?platform=fedora&arch={{ ansible_architecture }}
    dest: "{{ current_user_home }}/Downloads"
  register: spideroak_download

- name: Install SpiderOak
  dnf:
    name: "{{ spideroak_download.dest }}"
    state: present
  become: yes
