---
# tasks file for spideroak

- name: Ensure system architecture
  set_fact:
    spideroak_arch: "x64"
  when: ansible_facts['architecture'] == "x86_64"

- name: Ensure Fedora package dependencies
  include: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora' and spideroak_arch is defined

- name: Ensure Ubuntu package dependencies
  include: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu' and spideroak_arch is defined
