---
# tasks file for spideroak

- name: Ensure Fedora package dependencies
  include: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- name: Ensure Ubuntu package dependencies
  include: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'
