---
# tasks file for Funtoo keychain

- name: Download keychain
  get_url:
    url: http://www.funtoo.org/distfiles/keychain/keychain-{{ keychain_version }}.tar.bz2
    dest: "{{ current_user_home }}/Downloads"
  register: keychain_archive
  tags: keychain

- name: Unarchive keychain
  unarchive:
    src: "{{ keychain_archive.dest }}"
    dest: /opt
  become: yes
  register: keychain
  tags: keychain

- name: symlink keychain-version to keychain
  file:
    state: link
    src: /opt/keychain-{{ keychain_version }}
    dest: /opt/keychain
  become: yes
  tags: keychain

