---
# tasks file for ssh

- name: Ensure there is an .ssh directory
  file:
    path: "{{ current_user_home }}/.ssh"
    state: directory
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0700

## Funtoo keychain
- name: Funtoo keychain tasks
  include: funtoo-keychain.yml

