---
# tasks file for ssh

- name: Ensure there is an .ssh directory
  file:
    path: "{{ ansible_facts['user_dir'] }}/.ssh"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: 0700

## Funtoo keychain
- name: Funtoo keychain tasks
  include: funtoo-keychain.yml

