#!/bin/sh

required_packages="ansible git python2-dnf"

command_exists() {
  command -v "$@" > /dev/null 2>&1
}

run_bootstrap() {
  cd $HOME
  echo "Cloning dotfiles repo"
  git clone --recursive https://github.com/dailyherold/dotfiles.git .dotfiles
  cd .dotfiles/ansible

  # TODO: accept param to this script that can be passed onto ansible command e.g. --step
  ansible-playbook bootstrap.yml
}


echo "Installing packages: ${required_packages}"

sh_c='sh -c'

if [ "$user" != 'root' ]; then
  sh_c='sudo -E sh -c'
fi

$sh_c "dnf -y -q install ${required_packages}"

run_bootstrap
