---
# Using kubectl install instructions: https://kubernetes.io/docs/tasks/tools/install-kubectl/
#
- name: Add kubectl GPG key
  apt_key:
    state: present
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    validate_certs: no
  become: yes

- name: Add required packages
  apt:
    state: latest
    name: apt-transport-https
  become: yes

- name: Add Kubernetes repo
  apt_repository:
    state: present
    # Repo hardcoded according to install docs
    # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
  become: yes

- name: Install kubectl package
  apt:
    state: latest
    name: kubectl
    update_cache: yes
  become: yes
