---
# tasks file for kubernetes
#
- name: RedHat tasks
  include: redhat.yml
  when: "'redhat_family' in group_names"

- name: Debian tasks
  include: debian.yml
  when: "'debian_family' in group_names"

# https://github.com/kubernetes-sigs/aws-iam-authenticator
- name: Download AWS IAM authenticator
  get_url:
    url: "{{ iam_authenticator_url }}"
    dest: /usr/local/bin/aws-iam-authenticator
    mode: u=rwx,g=rx,o=rx
    validate_certs: false
  become: yes
