---
# tasks file for kubernetes
#
- name: Fedora tasks
  include: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- name: Ubuntu tasks
  include: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

# https://github.com/kubernetes-sigs/aws-iam-authenticator
- name: Download AWS IAM authenticator
  get_url:
    url: "{{ iam_authenticator_url }}"
    dest: /usr/local/bin/aws-iam-authenticator
    mode: u=rwx,g=rx,o=rx
    validate_certs: false
  become: yes
