---
# tasks file for kubernetes
#
- name: Fedora tasks
  include: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- name: Ubuntu tasks
  include: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Download Heptio AWS authenticator
  get_url:
    url: "{{ heptio_url }}"
    dest: /usr/local/bin
    mode: u=rwx,g=rx,o=rx
    validate_certs: false
  become: yes
