---
name: Steven Gerrard
nickname: stevieg
company: LiverpoolFC

dev_home: "/home/{{ current_user }}/dev"
custom_libinput: false
onlykey_support: false
thinkpad_workstation: false
dell_workstation: false

beyondcompare_version: "4.2.6.23150"

packages:
  - git
  - subversion
  - python-pip
  - python3-pip
  - wget
  - bzip2
  - tar
  - unzip
  - make # devtools
  - automake # devtools
  - cmake # devtools
  - gcc # devtools
  - sysstat # useful system stat utilities (mpstat, pidstat, iostat, sar, etc)

extra_packages:
  - vim
  - iotop
  - iftop
  - htop
  - ioping
  - ntp
  - tree
  - powertop
  #- smartmontools
  - traceroute
  - mtr
  - curl
  - wireshark
  - nmap
  - zsh
  - zsh-doc
  - jq
  - vpnc
  - tmux
  - remmina
  - xclip
  - awscli
  - zeal # offline documentation browser
  - guake # drop down terminal
  - shutter # awesome screenshots
  - gpaste # clipboard manager
  - i3lock # simple screen lock that doesn't do stupid gnome power management turn off screen stuff (despite me telling it not to)
  - stress # basic stress test terminal app
  - gawk # used by tmux-fingers plugin
  - openconnect # SWA vpn
  - qemu # qemu virtualization
  - qemu-kvm # qemu virtualization
  - snapd # snap package daemon
  - libinput-tools # helpful libinput commands like `libinput debug-events --device /dev/input/event8`
  - cifs-utils # for cifs mounts (e.g. samba)
  - vlc # for da videos
  - exfat-fuse # exfat filesystem support (e.g. HiBy R3)
  - exfat-utils # exfat filesystem support (e.g. HiBy R3)
  - net-tools # useful network tools e.g. netstat
  - pylint # python linter
  - gtypist # handy cli tool for typing better

snap_packages:
  - telegram-desktop # people chat
  - slack --classic # work chat and communities
  - helm --classic # Kubernetes package manager

debian_packages:
  - man
  - g++
  - linux-headers-generic
  - vim-gtk # for some additional xserver support (e.g. clipboard)
  - build-essential
  - openjdk-8-jdk
  - python-dev
  - python3-dev
  - python-apt # for Ansible's apt_repository module
  - ppa-purge
  - ack-grep
  - silversearcher-ag
  - tshark
  - lm-sensors # hardware sensors for temperature/RPM
  #- nautilus-dropbox # TODO add role for dropbox (or storage in general)
  - libvirt-bin # qemu virtualization
  - verse # bible verse package

redhat_packages:
  - man-pages
  - gcc-c++ # devtools
  - kernel-devel # devtools
  - vim-X11 # for some additional xserver support (e.g. clipboard)
  - java-1.8.0-openjdk-devel
  - python-devel
  - python3-devel # devtools
  - python2-dnf # for Ansible's dnf module
  - python-netaddr # used by Ansible for some network fu
  - libselinux-python # used by Ansible
  - ack
  - the_silver_searcher
  - wireshark-gtk
  - lm_sensors # hardware sensors for temperature/RPM
  - chrome-gnome-shell # needed for gnome extension installs via browser
  - dropbox
  - gpaste-ui # ui for gpaste

pip_modules:
  - boto3
  - awscli
  - virtualenv
  #- paramiko
  #- PyYAML
  #- Jinja2
  #- httplib2
  #- argparse
  #- six
