---
fullname: Steven Gerrard
nickname: stevieg
company: LiverpoolFC

dev_home: "{{ ansible_facts['user_dir'] }}/dev"
repo_home: "{{ ansible_facts['user_dir'] }}/repos"
custom_libinput: false
onlykey_support: false
thinkpad_workstation: false
dell_workstation: false

# Alternate distros of the Debian or RedHat family where ansible_facts['os_family'] != Debian or RedHat
debian_other_distros:
  - Pop!_OS
#redhat_other_distros:

beyondcompare_version: "4.3.7.25118"

ppa_repos:
  - ppa:obsproject/obs-studio
  - ppa:flexiondotorg/quickemu

packages:
  - git
  - python3-pip
  - wget
  - bzip2
  - tar
  - unzip
  - make # devtools
  - automake # devtools
  - cmake # devtools
  - gcc # devtools
  - sysstat # useful system stat utilities (mpstat, pidstat, iostat, sar, etc)

extra_packages:
  - vim
  - iotop
  - iftop
  - htop
  - ioping
  - ntp
  - tree
  - powertop
  #- smartmontools
  - traceroute
  - mtr
  - curl
  - wireshark
  - nmap
  - zsh
  - zsh-doc
  - jq
  - vpnc
  - tmux
  - remmina
  - xclip
  - gimp # GNU image manipulation program
  - zeal # offline documentation browser
  - guake # drop down terminal
  - gpaste # clipboard manager
  - stress # basic stress test terminal app
  - gawk # used by tmux-fingers plugin
  - openvpn # vpn
  - qemu # qemu virtualization
  - qemu-kvm # qemu virtualization
  - virt-manager # qemu virtualization
  - snapd # snap package daemon
  - libinput-tools # helpful libinput commands like `libinput debug-events --device /dev/input/event8`
  - cifs-utils # for cifs mounts (e.g. samba)
  - vlc # for da videos
  - net-tools # useful network tools e.g. netstat
  - pylint # python linter
  - gtypist # handy cli tool for typing better
  - gnome-tweak-tool # Graphical interface for advanced GNOME 3 settings
  - iperf3 # network throughput tester
  - ncdu # disk usage analyzer with ncurses interface
  - pv # tool for monitoring the progress of data through a pipeline
  - direnv # environment switcher for the shell
  - darktable # open source photography workflow application and raw developer
  - chrome-gnome-shell # gnome shell integration for extension installs via browser
  - ngrep # network packet analyzer
  - flameshot # awesome screen captures with markup
  - ffmpeg # multimedia magic

snap_packages:
  - install intellij-idea-community --classic # JetBrains IntelliJ Community Edition
  - install datagrip --classic # JetBrains DataGrip

debian_packages:
  - man
  - g++
  - linux-headers-generic
  - vim-gtk # for some additional xserver support (e.g. clipboard)
  - build-essential
  - python3-dev
  - python-apt # for Ansible's apt_repository module
  - ppa-purge
  - ack-grep
  - silversearcher-ag
  - tshark
  - lm-sensors # hardware sensors for temperature/RPM
  - libvirt-daemon-system # qemu virtualization
  - libvirt-clients # qemu virtualization
  - verse # bible verse package
  - nfs-common # for nfs mounting
  - quickemu # optimized VM helper (requires ppa:flexiondotorg/quickemu)

redhat_packages:
  - man-pages
  - gcc-c++ # devtools
  - kernel-devel # devtools
  - vim-X11 # for some additional xserver support (e.g. clipboard)
  - python3-devel # devtools
  - python3-dnf # for Ansible's dnf module
  - python-netaddr # used by Ansible for some network fu
  - libselinux-python # used by Ansible
  - ack
  - the_silver_searcher
  - wireshark-gtk
  - lm_sensors # hardware sensors for temperature/RPM
  - gpaste-ui # ui for gpaste
  - libvirt

pip_modules:
  - boto3
  - virtualenv
  - xkcdpass # passphrase generator inspired by [XKCD 936](http://xkcd.com/936/)
  #- paramiko
  #- PyYAML
  #- Jinja2
  #- httplib2
  #- argparse
  #- six
