---
name: Steven Gerrard
nickname: stevieg
company: LiverpoolFC

dev_home: "/home/{{ current_user }}/dev"
custom_vmmouse: false
onlykey_support: false
thinkpad_workstation: false

ant_version: "1.10.2"
beyondcompare_version: "4.2.4.22795"
terraform_version: "0.11.3"
docker_machine_version: "v0.13.0"
docker_compose_version: "1.20.1"
datagrip_version: "1.0.3"
eclipse_release_name: "oxygen"
eclipse_minor_version: "2"
slack_version: "slack-3.0.5-0.1.fc21.x86_64"



packages:
  - git
  - subversion
  - python-pip
  - wget
  - bzip2
  - tar
  - unzip
  - make # devtools
  - automake # devtools
  - cmake # devtools
  - gcc # devtools
  - gcc-c++ # devtools
  - kernel-devel # devtools
  - python-devel # devtools
  - python3-devel # devtools
  - java-1.8.0-openjdk-devel
  - sysstat # useful system stat utilities (mpstat, pidstat, iostat, sar, etc)
extra_packages:
  - vim-enhanced
  - iotop
  - iftop
  - htop
  - ioping
  - ntp
  - tree
  #- powertop
  #- smartmontools
  - traceroute
  - mtr
  - curl
  - wireshark
  - nmap
  - zsh
  - jq
  - vpnc
  - freerdp # used by vpnc for rdp hosts
  - tmux
  - redshift
  - redshift-gtk
  - remmina
  - xclip
  - awscli
  - zeal # offline documentation browser
  - guake # drop down terminal
  - shutter # awesome screenshots
  - dropbox
  - gpaste # clipboard manager
  - gpaste-ui # ui for gpaste
  - i3lock # simple screen lock that doesn't do stupid gnome power management turn off screen stuff (despite me telling it not to)
  - stress # basic stress test terminal app

debian_packages:
  - man
  - vim-gtk # for some additional xserver support (e.g. clipboard)
  - build-essential
  - python-dev
  - python-apt # for Ansible's apt_repository module
  - ppa-purge
  - ack-grep
  - silversearcher-ag
  - tshark
  - lm-sensors # hardware sensors for temperature/RPM

redhat_packages:
  - man-pages
  - vim-X11 # for some additional xserver support (e.g. clipboard)
  - python-devel
  - python2-dnf # for Ansible's dnf module
  - python-netaddr # used by Ansible for some network fu
  - libselinux-python # used by Ansible
  - ack
  - the_silver_searcher
  - wireshark-gtk
  - lm_sensors # hardware sensors for temperature/RPM
  - chrome-gnome-shell # needed for gnome extension installs via browser
