---
name: Steven Gerrard
nickname: stevieg
company: LiverpoolFC

dev_home: "/home/{{ current_user }}/dev"
custom_vmmouse: false

maven_version: "3.3.9"
gradle_version: "2.10"
ant_version: "1.9.6"
beyondcompare_version: "4.1.3.20814"
terraform_version: "0.6.11"
packer_version: "0.10.1"
vagrant_version: "1.8.1"
nvm_version: "0.31.0"
docker_compose_version: "1.7.0"
docker_machine_version: "v0.7.0"
datagrip_version: "1.0.3"
eclipse_release_name: "mars"
eclipse_minor_version: "2"



packages:
  - git
  - subversion
  #- gcc
  - python-pip
  - wget
  - bzip2
  - tar
  - unzip
  - make
  #- cmake
extra_packages:
  - vim-enhanced
  - iotop
  - iftop
  - htop
  - ioping
  - ntp
  - tree
  #- powertop
  #- smartmontools
  - traceroute
  - mtr
  - curl
  - wireshark
  - nmap
  - zsh
  - jq
  - vpnc
  - freerdp # used by vpnc for rdp hosts
  - tmux
  - redshift
  - redshift-gtk
  - remmina
  - xclip
  - awscli
  - guake # drop down terminal
  - shutter # awesome screenshots

debian_packages:
  - man
  - vim-gtk # for some additional xserver support (e.g. clipboard)
  - build-essential
  - python-dev
  - python-apt # for Ansible's apt_repository module
  - ppa-purge
  - ack-grep
  - silversearcher-ag
  - tshark

redhat_packages:
  - man-pages
  - vim-X11 # for some additional xserver support (e.g. clipboard)
  - python-devel
  - python2-dnf # for Ansible's dnf module
  - ack
  - the_silver_searcher
  - wireshark-gtk
