---
fullname: Steven Gerrard
nickname: stevieg
company: LiverpoolFC

dev_home: "/home/{{ ansible_facts['user_id'] }}/dev"
custom_libinput: false
onlykey_support: false
thinkpad_workstation: false
dell_workstation: false

beyondcompare_version: "4.2.6.23150"

ppa_repos:
  - 'ppa:jonathonf/vim'

packages:
  - git
  - subversion
  - python-pip
  - python3-pip
  - wget
  - bzip2
  - tar
  - unzip
  - make # devtools
  - automake # devtools
  - cmake # devtools
  - gcc # devtools
  - sysstat # useful system stat utilities (mpstat, pidstat, iostat, sar, etc)

extra_packages:
  - vim
  - iotop
  - iftop
  - htop
  - ioping
  - ntp
  - tree
  - powertop
  #- smartmontools
  - traceroute
  - mtr
  - curl
  - wireshark
  - nmap
  - zsh
  - zsh-doc
  - jq
  - vpnc
  - tmux
  - remmina
  - xclip
  - awscli
  - gimp # GNU image manipulation program
  - zeal # offline documentation browser
  - guake # drop down terminal
  - gpaste # clipboard manager
  - stress # basic stress test terminal app
  - gawk # used by tmux-fingers plugin
  - openvpn # vpn
  - qemu # qemu virtualization
  - qemu-kvm # qemu virtualization
  - snapd # snap package daemon
  - libinput-tools # helpful libinput commands like `libinput debug-events --device /dev/input/event8`
  - cifs-utils # for cifs mounts (e.g. samba)
  - vlc # for da videos
  - exfat-fuse # exfat filesystem support (e.g. HiBy R3)
  - exfat-utils # exfat filesystem support (e.g. HiBy R3)
  - net-tools # useful network tools e.g. netstat
  - pylint # python linter
  - gtypist # handy cli tool for typing better
  - gnome-tweak-tool # Graphical interface for advanced GNOME 3 settings
  - iperf3 # network throughput tester
  - ncdu # disk usage analyzer with ncurses interface
  - pv # tool for monitoring the progress of data through a pipeline
  - direnv # environment switcher for the shell

snap_packages:
  - install slack --classic # work chat and communities
  #- install helm --classic # Kubernetes package manager
  - install intellij-idea-community --classic # JetBrains IntelliJ Community Edition
  - install datagrip --classic # JetBrains DataGrip
  - install bcc # tools for BPF-based Linux IO analysis, networking, monitoring, and more
  - install bpftrace # high-level tracing language for eBPF
  - connect bpftrace:system-trace # connect bpftrace per documentation

debian_packages:
  - man
  - g++
  - linux-headers-generic
  - vim-gtk # for some additional xserver support (e.g. clipboard)
  - build-essential
  - openjdk-8-jdk
  - python-dev
  - python3-dev
  - python-apt # for Ansible's apt_repository module
  - ppa-purge
  - ack-grep
  - silversearcher-ag
  - tshark
  - lm-sensors # hardware sensors for temperature/RPM
  - libvirt-daemon-system # qemu virtualization
  - libvirt-clients # qemu virtualization
  - verse # bible verse package

redhat_packages:
  - man-pages
  - gcc-c++ # devtools
  - kernel-devel # devtools
  - vim-X11 # for some additional xserver support (e.g. clipboard)
  - java-1.8.0-openjdk-devel
  - python-devel
  - python3-devel # devtools
  - python2-dnf # for Ansible's dnf module
  - python-netaddr # used by Ansible for some network fu
  - libselinux-python # used by Ansible
  - ack
  - the_silver_searcher
  - wireshark-gtk
  - lm_sensors # hardware sensors for temperature/RPM
  - gpaste-ui # ui for gpaste
  - libvirt

pip_modules:
  - boto3
  - awscli
  - virtualenv
  #- paramiko
  #- PyYAML
  #- Jinja2
  #- httplib2
  #- argparse
  #- six
