---
name: Steven Gerrard
nickname: stevieg
company: LiverpoolFC

dev_home: "/home/{{ current_user }}/dev"
custom_vmmouse: false
thinkpad_workstation: false

ant_version: "1.9.6"
beyondcompare_version: "4.1.3.20814"
terraform_version: "0.6.11"
docker_machine_version: "v0.7.0"
datagrip_version: "1.0.3"
eclipse_release_name: "mars"
eclipse_minor_version: "2"
slack_version: "2.6.0-0.1.fc21"



packages:
  - git
  - subversion
  - python-pip
  - wget
  - bzip2
  - tar
  - unzip
  - make # devtools
  - automake # devtools
  - cmake # devtools
  - gcc # devtools
  - gcc-c++ # devtools
  - kernel-devel # devtools
  - python-devel # devtools
  - python3-devel # devtools
  - java-1.8.0-openjdk-devel
extra_packages:
  - vim-enhanced
  - iotop
  - iftop
  - htop
  - ioping
  - ntp
  - tree
  #- powertop
  #- smartmontools
  - traceroute
  - mtr
  - curl
  - wireshark
  - nmap
  - zsh
  - jq
  - vpnc
  - freerdp # used by vpnc for rdp hosts
  - tmux
  - redshift
  - redshift-gtk
  - remmina
  - xclip
  - awscli
  - guake # drop down terminal
  - shutter # awesome screenshots
  - dropbox

debian_packages:
  - man
  - vim-gtk # for some additional xserver support (e.g. clipboard)
  - build-essential
  - python-dev
  - python-apt # for Ansible's apt_repository module
  - ppa-purge
  - ack-grep
  - silversearcher-ag
  - tshark

redhat_packages:
  - man-pages
  - vim-X11 # for some additional xserver support (e.g. clipboard)
  - python-devel
  - python2-dnf # for Ansible's dnf module
  - ack
  - the_silver_searcher
  - wireshark-gtk
