---
- name: Update all packages
  dnf: name=* state=latest
  become: yes

- name: Install standard packages
  dnf: name={{ item }} state=latest
  become: yes
  with_items: "{{ packages }}"

- name: Install extra packages
  dnf: name={{ item }} state=latest
  become: yes
  with_items: "{{ extra_packages }}"

- name: Install redhat family packages
  dnf: name={{ item }} state=latest
  become: yes
  with_items: "{{ redhat_packages }}"

## Additional apps/packages
- name: Install Google Chrome
  dnf:
    name: google-chrome-stable
    state: latest
  become: yes

- name: Install Slack
  dnf:
    name: https://downloads.slack-edge.com/linux_releases/slack-{{ slack_version }}.x86_64.rpm
    state: latest
  become: yes
