---
- name: Update all packages
  dnf: name=* state=latest
  become: yes

- name: Install standard packages
  dnf:
    name: "{{ packages }}"
    state: latest
  become: yes

- name: Install extra packages
  dnf:
    name: "{{ extra_packages }}"
    state: latest
  become: yes

- name: Install redhat family packages
  dnf:
    name: "{{ redhat_packages }}"
    state: latest
  become: yes

# https://docs.snapcraft.io/core/install-fedora
- name: Support snap packages with classic confinement
  file:
    state: link
    src: /var/lib/snapd/snap
    dest: /snap

## Additional apps/packages
- name: Install Google Chrome
  dnf:
    name: google-chrome-stable
    state: latest
  become: yes
