---

- name: Install tlp dependencies
  dnf:
    name: "{{ packages }}"
    state: latest
  become: yes
  vars:
    packages:
    - tlp # power saving
    - tlp-rdw # optional, Radio Device Wizard
    - kernel-devel # optional, needed for the akmod packages below

- name: Mask systemd-rfkill.service to avoid tlp radio options
  systemd:
    name: systemd-rfkill
    masked: yes

- name: Add TLP repo
  dnf:
    name: "http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release-1.0-0.noarch.rpm"
    state: latest
  become: yes

- name: Install additional tlp thinkpad-specific packages
  dnf:
    name: "{{ packages }}"
    state: latest
  become: yes
  vars:
    packages:
    - akmod-tp_smapi # optional, tp-smapi is needed for battery charge thresholds, recalibration and specific status output of tlp-stat
    - akmod-acpi_call # optional, acpi-call is needed for battery charge thresholds and recalibration on Sandy Bridge and newer models (X220/T420, X230/T430 et al.)
