---
# tasks file for thinkpad
- name: Ensure Fedora package dependencies
  include: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'
 
- name: Ensure Ubuntu package dependencies
  include: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'
