---
# https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository

- name: Remove pre-existing packages
  apt:
    state: absent
    name: "{{ packages }}"
  become: yes
  vars:
    packages:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Install required packages
  apt:
    state: latest
    name: "{{ packages }}"
  become: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker GPG key
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
    validate_certs: no
  become: yes

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable
    state: present
  become: yes

- name: Install Docker package
  apt:
    state: latest
    name: "{{ packages }}"
    update_cache: yes
  become: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
