---

- name: Download and install docker-compose
  get_url:
    dest: "/usr/local/bin/docker-compose"
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    mode: "u+x,g+rx,o+rx"
    force: yes
  become: yes
  tags: docker-compose
