---
# tasks file for docker

- name: RedHat tasks
  include: redhat.yml
  when: "'redhat_family' in group_names"
 
- name: Debian tasks
  include: debian.yml
  when: "'debian_family' in group_names"

- name: Ensure docker group
  group:
    name: docker
    state: present
    system: yes
  become: yes

- name: Add current user into docker group
  user:
    append: yes
    groups: docker
    state: present
    name: "{{ ansible_facts['user_id'] }}"
  become: yes
  notify: restart-docker

- name: Include docker-compose
  include: docker-compose.yml
  when: install_docker_compose == true
