---
# tasks file for docker

- name: Fedora tasks
  include: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'
 
- name: Ubuntu tasks
  include: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Ensure docker group
  group:
    name: docker
    state: present
    system: yes
  become: yes

- name: Add current user into docker group
  user:
    append: yes
    groups: docker
    state: present
    name: "{{ ansible_facts['ansible_user_id'] }}"
  become: yes
  notify: restart-docker

- name: Include docker-compose
  include: docker-compose.yml
  when: install_docker_compose == true
