---
# https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository

- name: Install required packages
  apt:
    state: latest
    name: "{{ packages }}"
  become: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
    validate_certs: no
  become: yes

- name: Select stable channel
  shell: 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/docker-ce.list'

- name: Install Docker package
  apt:
    state: latest
    name: docker-ce
    update_cache: yes
  become: yes
