---
# https://github.com/alols/xcape
- name: (Fedora) Install packages
  dnf:
    name: "{{ packages }}"
    state: latest
  become: yes
  vars:
    packages:
    - git
    - gcc
    - make
    - pkgconfig
    - libX11-devel
    - libXtst-devel
    - libXi-devel
