---
# tasks file for xcape
- name: Ensure RedHat package dependencies
  include: redhat.yml
  when: "'redhat_family' in group_names"

- name: Ensure Debian package dependencies
  include: debian.yml
  when: "'debian_family' in group_names"

- name: Ensure install dir
  file:
    state: directory
    path: "{{ xcape_install_dir }}"

- name: Clone xcape repo
  git:
    repo: https://github.com/alols/xcape.git
    dest: "{{ xcape_install_dir }}/xcape"
    accept_hostkey: yes
    update: yes

- name: Make xcape
  shell: make
  args:
    chdir: "{{ xcape_install_dir }}/xcape"
    creates: "{{ xcape_install_dir }}/xcape/xcape"
  register: make_result
 
- name: Make install xcape
  shell: make install
  args:
    chdir: "{{ xcape_install_dir }}/xcape"
  become: yes
  when: make_result.changed

