---
# https://github.com/alols/xcape
- name: (Ubuntu) Install packages
  apt:
    name: "{{ packages }}"
    state: latest
  become: yes
  vars:
    packages:
    - git
    - gcc
    - make
    - pkg-config
    - libx11-dev
    - libxtst-dev
    - libxi-dev
