---


# tasks file for photography
#
# Newest Darktable with settings https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable
# dev version of lensfun perhaps? (no z lenses on 3.2)
# liblensfun-bin
# fdupes
# rapidphotodownloader
# 7zz for Nikon firmware dmg extracting
# NFS requirements for NAS mounts
# exiftool for exif modifications (e.g. correcting date on photos)
# /usr/share/thumbnailers/gdk-pixbuf-thumbnailer.thumbnailer edit for file manager nef thumbnail support
# ffmpeg
# pick a DAM
#
# ## Video
# sudo apt install v4l2loopback-dkms v4l2loopback-utils
# sudo modprobe v4l2loopback video_nr=10 card_label="OBS Video Source" exclusive_caps=1
# guvcview
