---
# tasks file for jetbrains

- name: Fedora/Korora tasks
  include: fedora.yml
  when: ( ansible_distribution == 'Korora') or ( ansible_distribution == 'Fedora' )

- name: Ensure Ubuntu tasks
  include: ubuntu.yml
  when: ( ansible_distribution == 'Ubuntu') or ( ansible_distribution == 'Debian' )

# Used by Jetbrains IDEs
# https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
- name: Set custom inotify watches limit
  copy:
    dest: /etc/sysctl.d/60-jetbrains.conf
    src: 60-jetbrains.conf
  become: yes

# Jetbrains DataGrip
- name: Download DataGrip
  get_url:
    dest: "{{ current_user_home }}/Downloads"
    url: https://download.jetbrains.com/datagrip/datagrip-{{ datagrip_version }}-custom-jdk-linux.tar.gz
    validate_certs: no
  register: datagrip_archive
  tags: datagrip

- name: Unarchive DataGrip
  unarchive:
    dest: "{{ current_user_home }}"
    src: "{{ datagrip_archive.dest }}"
  tags: datagrip

# IntelliJ
- name: Download IntelliJ IDEA Community edition
  get_url:
    dest: "{{ current_user_home }}/Downloads"
    url: "{{ jetbrains_download_base_url }}/idea/ideaIC-{{ intellij_version }}.tar.gz"
    validate_certs: no
  register: intellij_archive
  tags: intellij

- name: Unarchive DataGrip
  unarchive:
    dest: /opt
    src: "{{ intellij_archive.dest }}"
  become: yes
  register: intellij_dest
  tags: intellij

- debug: var=intellij_dest
