---
# VirtualBox
- name: Install dkms
  apt:
    name: dkms
    state: latest
  become: yes
  tags: ["virtualbox","packages"]

- name: Configure the Oracle APT key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  become: yes
  tags: virtualbox

- name: Configure the VirtualBox APT repositories
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian trusty contrib"
    state: present
  become: yes
  tags: virtualbox

- name: Install virtualbox
  apt:
    update_cache: yes
    name: virtualbox-{{ virtualbox_version }}
    state: latest
  become: yes
  tags: ["virtualbox","packages"]

# Install extension pack as well
