---
# VirtualBox
- name: Install dkms
  apt:
    name: dkms
    state: latest
  become: yes
  tags: ["virtualbox","packages"]

- name: Configure the VirtualBox APT repositories
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_facts['distribution_release'] }} contrib"
    state: present
  become: yes
  tags: virtualbox

- name: Install virtualbox
  apt:
    update_cache: yes
    name: virtualbox-{{ virtualbox_version }}
    state: latest
  become: yes
  tags: ["virtualbox","packages"]

# Install extension pack as well
