---
# defaults file for java

oracle_arch: i586
oracle_version_major: 8
oracle_version_minor: 111
oracle_version_build: b14
oracle_url: http://download.oracle.com/otn-pub/java/jdk/{{ oracle_version_major }}u{{ oracle_version_minor }}-{{ oracle_version_build }}/jdk-{{ oracle_version_major }}u{{ oracle_version_minor }}-linux-x64.rpm

openjdk7_headless_url: https://kojipkgs.fedoraproject.org//packages/java-1.7.0-openjdk/1.7.0.79/2.5.5.0.fc20/x86_64/java-1.7.0-openjdk-headless-1.7.0.79-2.5.5.0.fc20.x86_64.rpm
openjdk7_url: https://kojipkgs.fedoraproject.org//packages/java-1.7.0-openjdk/1.7.0.79/2.5.5.0.fc20/x86_64/java-1.7.0-openjdk-1.7.0.79-2.5.5.0.fc20.x86_64.rpm
openjdk7_devel_url: https://kojipkgs.fedoraproject.org//packages/java-1.7.0-openjdk/1.7.0.79/2.5.5.0.fc20/x86_64/java-1.7.0-openjdk-devel-1.7.0.79-2.5.5.0.fc20.x86_64.rpm
