---
# Using Sublime install instructions: https://www.sublimetext.com/docs/3/linux_repositories.html
#
- name: Add Sublime GPG key
  apt_key:
    state: present
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    validate_certs: no
  become: yes

- name: Add required packages
  apt:
    state: latest
    name: apt-transport-https
  become: yes

- name: Select stable channel
  shell: 'echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list'

- name: Install Sublime Text and Merge packages
  apt:
    state: latest
    name: "{{ packages }}"
    update_cache: yes
  become: yes
  vars:
    packages:
    - sublime-text
    - sublime-merge
