---
# tasks file for sublime
#
- name: RedHat tasks
  include: redhat.yml
  when: "'redhat_family' in group_names"

- name: Debian tasks
  include: debian.yml
  when: "'debian_family' in group_names"
